# Generated by Django 3.2 on 2021-05-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_group_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group_posts',
            new_name='group',
        ),
    ]
