# Generated by Django 3.2 on 2021-05-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_title'),
        ('posts', '0004_auto_20210505_0036'),
    ]

    operations = [
    ]
