# Generated by Django 3.2 on 2021-05-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
