# Generated by Django 3.2 on 2021-05-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
