# Generated by Django 3.2 on 2021-05-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0003_auto_20210504_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/default.jpg', upload_to='users/images/'),
        ),
    ]
