# Generated by Django 3.2 on 2021-05-04 14:40

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=255),
        ),
    ]
