# Generated by Django 3.2 on 2021-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210504_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, default='images/default_group.jpg', null=True, upload_to='groups/images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
